### ISSUE TITLE
Debugging with GnuCOBOL 3.1.2  (VS) x86 

### ISSUE THREAD

**Issue by akbrant** [mridoni/gix#34] opened 2021-12-10 16:30 UTC
HI, 

 Your install tool is really nice for setting up GnuCOBOL both the MingW and VS versions.  I also like how gix deals with build artifacts and switching between x86/x64 build. 

I'm running in windows and can compile a simple hello world Cobol program with MingW and VS as x86.  I can set break points and can step through code when I build with MingW but not VS.  

Any clues on what am i missing?   Is debugging with VS build even possible? 

O to debug with VS build of GNUCobol would be the most wonderful thing for me.  I'm force to use the VS build as the tool chain I must use only works with the VS build.

Thanks,
Brant

[PROJ1_CODE.txt](https://github.com/mridoni/gix/files/7694076/PROJ1_CODE.txt)

[build_MING.txt](https://github.com/mridoni/gix/files/7694084/build_MING.txt)
[debug_MING.txt](https://github.com/mridoni/gix/files/7694085/debug_MING.txt)

[build_VS.txt](https://github.com/mridoni/gix/files/7694092/build_VS.txt)
[debug_VS.txt](https://github.com/mridoni/gix/files/7694095/debug_VS.txt)

![trysimpledebugVS](https://user-images.githubusercontent.com/1112030/145608551-0d1a46b6-f1ae-4eff-92eb-1d9e6fbebd77.PNG)

**Comment by mridoni** [comment] 2021-12-23 11:21
Hello,
sorry for being so late in replying, but I was outside of the country for a
few weeks.

I'll have to check, but debugging with Visual Studio is surely possible,
it's the main target I test with. It might have something to do with x86
(instead of x64), I have to check this.



Il giorno ven 10 dic 2021 alle ore 17:30 akbrant ***@***.***>
ha scritto:

**Comment by mridoni** [comment] 2021-12-23 13:58
Confirmed, it is a bug with x86, it works on x64. I'll try to fix it before the next release (probably and hopefully around mid-January)

**Comment by akbrant** [comment] 2021-12-24 01:11
Wow,  Ok thanks for checking it out.  Looking forward to the fix.

**Comment by mridoni** [comment] 2021-12-24 09:04
Found it. Basically due to a bug some flags in the module loading/checking phase of the debugger were checked the wrong way for x86 and the module being loaded was not recognized as a GnuCOBOL module, so the debugger unceremoniously ignored it. Unfortunately we need to have two slightly different code paths in some points because symbols work (just) a bit differently on x64 and x86, and this time the x86 path contained an error. 

The fix will be part of the next release (around mid-January).

**Comment by mridoni** [comment] 2021-12-24 09:05
Just to be clear, in the comment above, i am talking in the context of Visual Studio + x86/x64.

**Comment by mridoni** [comment] 2022-02-24 09:00
Closing, this was fixed in v1.0.7

**Closed by mridoni** 2022-02-24 09:00 UTC
Labels: bug

**Comment by akbrant** [comment] 2022-02-24 10:12
shit I've been meaning to get back to this.  Yes its fixed.  but.... when i open a few files gix crash. ill open new issue
