### ISSUE TITLE
How to work with bytea / lob

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#33] opened 2021-12-07 15:13 UTC
Is it possible to work on these with `PIC` ... `VARYING`?

For people that don't know about the internal types: to handle `VARCHAR` without explicit space trim/pad it is possible in upstream (may have been added after the fork, not sure when either of those happened) to declare a host variable as "PIC X VARYING" the following way:

```cobol
01 BINARY-DB-FIELD     PIC X(50000) VARYING.
```
and the [preparser then converts that](https://github.com/opensourcecobol/Open-COBOL-ESQL/blob/4f80b1bb49e0ca3f5429664441f8399cef4f8a64/ocesql/ppout.c#L1455) to

```cobol
01 BINARY-DB-FIELD.
    03 BINARY-DB-FIELD-LEN   PIC S9(8) COMP-5.
    03 BINARY-DB-FIELD-ARR   PIC X(50000).
```

Within the COBOL program, before/after using the host variable `:BINARY-DB-FIELD` the length is then set/read.

The questions are:
* Is this supportedin GixSQL already, too?
* Can that be handled the same way with the BLOB data types (or PostgreSQL data types `bytea` and/or with lob)?

... second check: before this is done specification of variable types seems to be necessary to be added first, in this case:
```
EXEC SQL    VAR BINARY-DB-FIELD IS VARBINARY END-EXEC
```
... or the [DB2 variant](https://www.ibm.com/docs/en/db2-for-zos/11?topic=cobol-host-variables-in):

```cobol
01 BINARY-DB-FIELD     SQLTYPE IS VARBINARY(50000).
```

As the repo search does not result in anything on the parser side for VARBINARY I _assume_ that this doesn't work yet. Is that correct?

**Comment by GitMensch** [comment] 2022-01-31 16:08
I'm quite sure that one thing currently does not work: plain `PIC X` to `bytea` (actually that works, but not the other way around). If wanted I could do a PR to fix this.

**Comment by mridoni** [comment] 2022-01-31 17:05
I'll look into it, but I don't know if this will be part of the next release, for which I am targeting the second half of February (usual caveats about time constraints apply, of course)

**Comment by GitMensch** [comment] 2022-01-31 17:06
Sounds fair.

**Comment by GitMensch** [comment] 2022-02-01 19:59
Just an update: I've did a local bugfix to the "C" version with the following function (and calling it for alphanumeric/national cases in [`create_coboldata()`](https://github.com/mridoni/gix/blob/2371dba4a58c0ae67d43f52c4cfa30f2fa1fe4b8/gixsql/libgixsql/SqlVar.cpp#L449)):

```c
static char *
decode_if_necessary (char *retstr, size_t *rlen)
{
	const size_t rstrlen = strlen(retstr);
	char const *retstr_end = retstr + rstrlen;
	*rlen = rstrlen; /* common case: not encoded */

	if (rstrlen < 4 || rstrlen % 2 || memcmp(retstr, "\\x", 2)) {
		/* definitely not encoded - just pass back original string */
		return retstr;	
	}
	/* looks like an encoded string - prevalidate actual data */
	{
		char *p = retstr + 2;
		while (p != retstr_end) {
			if (!isxdigit(*p)) {
				/* not fully matching encoding - pass back original string */
				return retstr;	
			}
			p++;
		}
	}
	/* data is fine - so translate, then adjust length and
	   return the pointer to the freshly allocated buffer
	   (which the caller has to free) */
	{
		/* note: rstrlen contains the possible prefix,
		         so trailing nul is taken care of */
		char *buff = malloc (rstrlen / 2);
		size_t i = 0;
		for (retstr += 2; retstr != retstr_end; retstr += 2) {
			int char_val;
			sscanf(retstr, "%2x", &char_val);
			buff[i++] = (char)char_val;
		}
		buff[i] = 0;
		*rlen = i;
		return buff;
	}
}
```

Testing showed: reading bytea data works fine now.

... but: writing only works until you get to a binary zero because  `createRealData()]` uses a `strdup` to get the data in - which [is not done in this repo](https://github.com/mridoni/gix/blob/2371dba4a58c0ae67d43f52c4cfa30f2fa1fe4b8/gixsql/libgixsql/SqlVar.cpp#L128) so I hope my planned fix to stay with memcpy will be enough - we'll see tomorrow (if not then the data may need encoding).

**Comment by mridoni** [comment] 2022-02-02 13:37
Ok, thank you a lot! The problem is that in GixSQL this has to be moved to the "driver" level, since we are not only supporting PostgreSQL (like ocesql does), but also MySQL and ODBC - and, ideally, other DBMSs - and we cannot obviously apply the same parsing rules for binary data (or whatever else, for that matter). All of this makes your otherwise perfectly fine solution more complicated to apply but I'll have to dig deeper when I get there.

Thanks again.

**Comment by GitMensch** [comment] 2022-02-02 19:15
Mini-update to keep this discussion on: seems like the simple `memcpy` did not help with the binary data getting into. I'll verify that tomorrow and then likely check with the encoding backwards (which I _guess_ will possibly go in "as text") and if this doesn't work then the use of bytea in its current form would mean "apply the ~hack~ patch and leave reading as is - or split that out to a special insert that explicit encodes in the query and for writing _always_ do a separate specially crafted statement" (I hope to get around of this, but again - we'll see, I'll keep the updates here).

**Comment by GitMensch** [comment] 2022-02-03 12:58
After another longer debugging session I can now give the answer: as is: handle it in the COBOL side.

The reason: even if all the data is setup correctly (from what I've glanced over this is the case here) the is no chance at all that it could work on the way to the DB directly, because with all driver parts only the data is send in - as string. The length and type parameters are all empty (and the pg one uses the "text format" in `PQexecParams` and friends so any data that does not match it would have to be converted in both ways (and I'm not sure that this would even work).

If the COBOL side works - which is under tests next - then this isn't necessary a problem and #47 maybe could tackle that.

**Comment by mridoni** [comment] 2022-02-03 15:43
Ok, I'll have a look at it anyway, thanks for your work.

**Comment by mridoni** [comment] 2022-02-05 12:00
One thing that I forgot to mention: VARCHAR fields are already supported, they must be defined as level 49, e.g.

     01  Column-name
            49  Column-name-len    PIC 9(02)  BINARY.
            49  Column-name-data   PIC  X(273).

Currently only 16 bit length indicator is supported, with a supported column size of max 64k (yes, this doesn't correspond to the example above, but I am writing from my phone and I don't have the code with me).

**Comment by GitMensch** [comment] 2022-02-06 08:49
Sounds like a documentation issue (and like a thing to add to a new file gixsql/TODO). Also if/when #47 is implemented column-name can just be specified as different kind of VARCHAR/VARBINARY and the internal structure can be recognized with different length indicators and without the level 49 restriction.

**Comment by mridoni** [comment] 2022-02-11 18:24
Good news: I made progress on this (you will find a sample program and a output dump at the end of this message):

- Added "SQL TYPE IS"-style declaration, so you can declare variables like this

           01 BFLD SQL TYPE IS BINARY(100).
           01 VBFLD SQL TYPE IS VARBINARY(100).
           
           01 CFLD SQL TYPE IS CHAR(100).
           01 VCFLD SQL TYPE IS VARCHAR(100).      

Variable length fields are converted into "level 49"-style declarations by the preprocessor (a compile-time option allows to generate 2 or 4 bytes indicator fields)

- bytea fields in PostgreSQL are automatically converted to binary data for fields declared as BINARY/VARBINARY. Should you need the unconverted encoded output from the DB (e.g. '\xdeadbeef'), this function can be disabled with a parameter in the new and improved format for the data source connection string (obviously you will probably want to handle this as text, not binary data), e.g.

    pgsql://localhost:5432/testdb?decode_binary=off

The binary handling code can be easily extended for other DBMSs, it should be just a few lines of code (binary data is still not supported in the MySQL and ODBC drivers, but is coming).

Some miscellaneous additions:

- Autocommit and client encoding can be set using the parameters in the data source connection string
- A default schema/database can be selected upon connection (PostgreSQL/MySQL)
- Memory for "real" (i.e. display) data is now only allocated once
- Fixed a few bugs in the library driver (SQLERR handling, some error conditions are handled instead of causing a crash, etc.)
- Fixed a few bugs in the preprocessor (some error conditions are handled instead of causing a crash)

I had to move a lot of stuff around and change a lot of things in the code so, in turn, a lot of testing is in order. For now the release timeline I had in mind (more or less the end of February) is maintained, but its staying there obviously depends on what comes out of the tests I am writing and running.

This is the test program I have been using for testing the binary/varbinary feature (more will come, obviously):

       IDENTIFICATION DIVISION.
       
       PROGRAM-ID. TSQL005A. 
       
       
       ENVIRONMENT DIVISION. 
       
       CONFIGURATION SECTION. 
       SOURCE-COMPUTER. IBM-AT. 
       OBJECT-COMPUTER. IBM-AT. 
       
       INPUT-OUTPUT SECTION. 
       FILE-CONTROL. 
       
       DATA DIVISION.  
       
       FILE SECTION.  
       
       WORKING-STORAGE SECTION. 
       
           01 DATASRC PIC X(64).
           01 DBUSR  PIC X(64).

           01 BFLD SQL TYPE IS BINARY(100).
           01 VBFLD SQL TYPE IS VARBINARY(100).
           
           01 CFLD SQL TYPE IS CHAR(100).
           01 VCFLD SQL TYPE IS VARCHAR(100).      

           01 NUM1          PIC 99V99.

           01 TOT           PIC 9(8).
           
           01 SDIGIT.
              03 SDIGIT01 PIC X(1).
              03 SDIGIT02 PIC X(1).
                
           01 NDIGIT REDEFINES SDIGIT PIC S9(04) COMP.


       EXEC SQL 
            INCLUDE SQLCA 
       END-EXEC. 
         
       PROCEDURE DIVISION. 
 
       000-CONNECT.

           DISPLAY "DATASRC" UPON ENVIRONMENT-NAME.
           ACCEPT DATASRC FROM ENVIRONMENT-VALUE.
           DISPLAY "DATASRC_USR" UPON ENVIRONMENT-NAME.
           ACCEPT DBUSR FROM ENVIRONMENT-VALUE.
           
           DISPLAY '***************************************'.
           DISPLAY " DATASRC  : " DATASRC.
           DISPLAY " AUTH     : " DBUSR.
           DISPLAY '***************************************'.

           EXEC SQL
              CONNECT TO :DATASRC USER :DBUSR
           END-EXEC.      
           
           IF SQLCODE <> 0 THEN
              DISPLAY 'CONNECT SQLCODE. ' SQLCODE
              DISPLAY 'CONNECT SQLERRM. ' SQLERRM
              GO TO 100-EXIT
           END-IF.

       100-MAIN.

           EXEC SQL
              SELECT BFLD, VBFLD, CFLD, VCFLD, NUM1 
                INTO :BFLD, :VBFLD, :CFLD, :VCFLD, :NUM1 FROM BINTEST
           END-EXEC.
           
           IF SQLCODE <> 0 THEN
              DISPLAY 'SELECT SQLCODE. ' SQLCODE
              DISPLAY 'SELECT SQLERRMC. ' SQLERRMC
              GO TO 100-EXIT
           END-IF.
           
           MOVE LOW-VALUES TO SDIGIT01.
           MOVE LOW-VALUES TO SDIGIT02.

           MOVE VBFLD-DATA(1:1) TO SDIGIT02.
           DISPLAY 'DIGIT: ' NDIGIT.

           MOVE VBFLD-DATA(2:1) TO SDIGIT02.
           DISPLAY 'DIGIT: ' NDIGIT.

           MOVE VBFLD-DATA(83:1) TO SDIGIT02.
           DISPLAY 'DIGIT: ' NDIGIT.

           DISPLAY 'BFLD        : [' BFLD ']'.
           DISPLAY 'BFLD LENGTH: ' LENGTH OF BFLD.

           DISPLAY 'VBFLD-DATA  : [' VBFLD-DATA(1:VBFLD-LENGTH) ']'.
           DISPLAY 'VBFLD-DATA  : [' VBFLD-DATA(1:88) ']'.
           DISPLAY 'VBFLD-LENGTH: ' VBFLD-LENGTH.

           DISPLAY 'CFLD        : [' CFLD ']'.
           DISPLAY 'CFLD LENGTH: ' LENGTH OF CFLD.

           DISPLAY 'VCFLD-DATA  : [' VCFLD-DATA(1:VCFLD-LENGTH) ']'.
           DISPLAY 'VCFLD-LENGTH: ' VCFLD-LENGTH.

           EXEC SQL
              CONNECT RESET
           END-EXEC.      
           
           IF SQLCODE <> 0 THEN
              DISPLAY 'DISCONNECT SQLCODE. ' SQLCODE
              DISPLAY 'DISCONNECT SQLERRM. ' SQLERRM
              GO TO 100-EXIT
           END-IF.
       
       100-EXIT. 
             STOP RUN.

I created a test table like this (the numeric column is not used in the test):

    create table bintest (bfld bytea, vbfld bytea, cfld char(100), vcfld varchar(100), num1 numeric(4,2))

and filled it like this:

    insert into bintest (bfld, vbfld, cfld, vcfld, num1) values (@p_1, @p_2, 'ABCDEFGHIJK', 'ABCDEFGHIJK', 12.34)

@p1 and @p2 are two 80-bytes long binary buffers filled with values from 33 to 112 (ASCII chars, to be able to print something that made sense), here it is from my test case (in C#):

    const int DATA_SZ = 80;
    const int DATA_START = 33;  // starts with "!"
    data = new byte[DATA_SZ];
    for (int i = 0; i < DATA_SZ; i++)
        data[i] = (byte)(DATA_START + i);

This is the output (the zero values have been replaced here with 'º'):

    Output: C:\Users\marchetto\source\repos\gix-ide-gixsql-post-1.0.7\tmp_test\TSQL005A.exe (17920 bytes)
    Running TSQL005A.exe 
    ***************************************
     DATASRC  : pgsql://localhost:5432/testdb1                                  
     AUTH     : test.test                                                       
    ***************************************
    DIGIT: +0033
    DIGIT: +0034
    DIGIT: +0167
    BFLD        : [!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopºººººººººººººººººººº]
    BFLD LENGTH: 100
    VBFLD-DATA  : [!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnop]
    VBFLD-DATA  : [!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopºººººººº]
    VBFLD-LENGTH: 0080
    CFLD        : [ABCDEFGHIJK                                                                                         ]
    CFLD LENGTH: 100
    VCFLD-DATA  : [ABCDEFGHIJK]
    VCFLD-LENGTH: 0011

Hope to have more news soon.

**Comment by GitMensch** [comment] 2022-02-12 08:53
Sounds quite cool. I'm away until end of February, so its last day would suit me perfectly fine, but more testing is better than an early release.

I'm any case please add all of your test cases to a test directory, the parsing tests can perfectly be run automated (especially interesting for error handling), I could set up autoconf generated tests (as with GnuCOBOL, mostly needs a shell and working diff) after the release from existing tests, too.
For bytea it will be very good to have x'00' included in the tests, as it will commonly be cut when C string operations are done with it, so it is interesting to see if the data that was retrieved from the db back still contains the data after it.

What I was wondering about with BLOB/bytea on return: why would there be a fixed length returning field in COBOL? I think at least one COBOL db library has an option to first get you the return length and with a second call gets you the actual data (without a second roundtrip to the db), but this may be mis-remembered.

It would also be possible (and maybe much cleaner) to have a special VARBINARY definition that returns size and a pointer to the data - the programmer needs to do something with the pointer (like manually allocating a field of the size length) to keep that.

Would it be possible to also support the EXEC SQL VAR style?

**Comment by GitMensch** [comment] 2022-02-12 18:09
For `EXEC SQL VAR` see [ProCOB doc - Datatype Equivalencing](https://docs.oracle.com/cd/A57673_01/DOC/api/doc/PCO18/ch1.htm#toc021).

Possibly relevant for compatibility in general (most can be supported without a switch): [MF docs for ProCOB compat](https://www.microfocus.com/documentation/visual-cobol/vc50pu2/VS2019/GUID-3492935C-7CBE-4055-A831-B2892E9EB056.html)

For the special var and varbinary types I've thought about something like the following (would be **not** compatible to any other preprocessor I know of, but I'd find that quite useful):

`01 DB-DATA TYPE IS VARBINARY-POINTER` which would be translated to:

```cobol
01 DB-DATA.
   05 DB-DATA-LEN    USAGE BINARY-LONG. *> or whatever you find reasonable
   05 DB-DATA-PTR    USAGE DATA-POINTER. *> or POINTER if you like that more
```

When it would be used as a target for a `SELECT` via `:DB-DATA` the COBOL program could do something like this:

GnuCOBOL only:
```cobol
UNSTRING FUNCTION CONTENT-OF(MY-DATA-PTR, MY-DATA-LEN) ...
```

More portable (even more when dropping the `UNBOUNDED` part):
```cobol
LINKAGE SECTION.
01 REAL-DATA.   *> NOT referenced in PROCEDURE DIVISION USING
    05 FILLER OCCURS UNBOUNDED DEPENDING ON DB-DATA-LEN.
....
*> after SELECT:
SET ADDRESS OF REAL-DATA TO DB-DATA-PTR.
UNSTRING REAL-DATA ...
```

The point here is that libgixsql provides the storage, let it "leak" to the program and on next call into libgixsql would go to its "leak" list (there could be multiple of those parameters be used in a single `SELECT`) and `free` (or destroy) the data [or just pass on the data from the db driver - if there is anything - and let the db driver free that storage].

Similar for `UPDATE` or `INSERT`, but in this case the COBOL program would provide the length and storage:

```cobol
WORKING-STORAGE SECTION.
01 some-record.
   ...
   05 SOME-DATA PIC X(512).
LINKAGE SECTION.
01 OTHER-DATA PIC X ANY LENGTH.   *> referenced in PROCEDURE DIVISION USING
....

SET DB-DATA1-PTR TO ADDRESS OF SOME-DATA
MOVE LENGTH OF SOME-DATA TO DB-DATA1-LEN
SET DB-DATA2-PTR TO ADDRESS OF OTHER-DATA
MOVE FUNCTION LENGTH (OTHER-DATA) TO DB-DATA2-LEN

*> then use :DB-DATA1 and :DB-DATA2
```

Those options would make "generic" db programs in COBOL much more easy, also storing and receiving of "some data" (like XMLs or similar) into/from VARBINARY fields in the DB.

**Comment by mridoni** [comment] 2022-02-13 11:29
The only problem I see is when to invalidate/free the allocated memory in the driver, but doing it in SELECT..INTO and FETCH statements should be enough. Unfortunately using the memory allocated by the native drivers (e.g. libpq, libmysql) is not an option because each driver handles memory allocation in a different way.

This will probably not be in the next release (I am also not sure about the "EXEC SQL VAR" thing) but I am surely going to schedule it for the release after that: it shouldn't take too long to implement, actually, but I would like not to postpone the release of v1.0.8.

**Comment by mridoni** [comment] 2022-02-13 12:06
> For EXEC SQL VAR see [ProCOB doc - Datatype Equivalencing](https://docs.oracle.com/cd/A57673_01/DOC/api/doc/PCO18/ch1.htm#toc021).

Ok, I read it. Given the way GixSQL works, I think this currently only makes sense for BINARY/VARBINARY datatypes: all the other types are extracted from the DB in text format and converted before setting the values of the COBOL variables (VARCHAR too, there is some extra processing to return the data length into the level-49 length indicator but the data is obviously just text). When I get to it, I will implement parsing for the other types (float, decimal, etc.) anyway. 

Then it might be interesting to handle the data returned by libpq as binary data: this might be faster and useful for some datatypes, but it's going to be quite an effort, because each DBMS type must be mapped and converted individually, and I am not sure the speed gain is worth the additional work.

**Comment by mridoni** [comment] 2022-02-22 15:39
Introduced support in [v1.0.8](https://github.com/mridoni/gix/releases/tag/v1.0.8)

**Closed by mridoni** 2022-02-22 15:39 UTC
Labels: enhancement

**Comment by GitMensch** [comment] 2022-03-28 09:30
It seems the following was either dropped or did not work with GixSQL before:

```cobol
01 BINARY-DB-FIELD     PIC X(50000) VARYING.
```
> and the [preparser then converts that](https://github.com/opensourcecobol/Open-COBOL-ESQL/blob/4f80b1bb49e0ca3f5429664441f8399cef4f8a64/ocesql/ppout.c#L1455) to
> 
```cobol
01 BINARY-DB-FIELD.
    03 BINARY-DB-FIELD-LEN   PIC S9(8) COMP-5.
    03 BINARY-DB-FIELD-ARR   PIC X(50000).
```

Manually doing the translation seems to work.
